import Head from 'next/head'
import Image from 'next/image'
// import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-gradient-to-b from-zinc-800 to-zinc-900  min-h-screen font-body '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header className='flex-col border-b-2 border-zinc-50'> 
            <h1 className='pt-4 pb-10 px-6 font-display text-zinc-50 font-bold text-2xl'>FORTH ROAD</h1> 
        </header>

      <main className='divide-y-2 text-zinc-50 py-2'>
          <section idName='splash' className='lg:px-6'>
              <div idName='banner' className='w-full lg:5/6 mx-auto lg:flex-row'>
                  <div idName='image' className='relative lg:w-5/6'>
                      <h1 className='font-bold absolute bottom-0 right-0 text-4xl lg:text-8xl'>EASY DAYS</h1>
                      <img src="https://f.eu1.jwwb.nl/public/q/y/c/temp-ukdcxzhwnxxxdixfgkhr/easy.jpeg" className='w-full lg:w-4/6 '></img>
                  </div>
                  <div idName='socials' className='flex lg:flex-col w-full lg:w-1/5'>
                      <div className='w-1/5'>tw</div>
                      <div className='basis-1/5'>fb</div>
                      <div className='basis-1/5'>in</div>
                      <div className='basis-1/5'>tt</div>
                      <div className='basis-1/5'>yt</div>
                  </div>
              </div>
              <div idName='info'>
                  hello
              </div>

          </section>
          <section idName='discog' className=' lg:px-6 w-full pl-4'>
              <h1 className='font-bold w-full pb-4'>DISCOGRAPHY</h1>
              <div className='relative'>
                  <ul className='w-4/6 pl-4'>
                      <li className='pb-2'><span className='pr-6'>2022</span>play it again</li>
                      <li className='pb-2'><span className='pr-6'>2021</span>i don't even mind</li>
                      <li className='pb-2'><span className='pr-6'>2021</span>L.O.V.E</li>
                      <li className='pb-2'><span className='pr-6'>2021</span>cherry lemonade</li>
                  </ul>
              <div className='absolute top-0 right-0 w-3/6'>
                  <img src="https://t.eu1.jwwb.nl/W1495710/6NtMPTbsG2_LR0j24e35r1-yq2Q=/340x0/filters:quality(95)/f.eu1.jwwb.nl%2Fpublic%2Fq%2Fy%2Fc%2Ftemp-ukdcxzhwnxxxdixfgkhr%2Fk6aqj0%2Feasy1.jpeg"></img>
          </div>
              </div>
          </section>
          <section idName='tour' className='lg:px-6 '>
              <h1 className='font-bold'>TOUR</h1>
              <div>
                  <ul className=''>
                      <li className='pb-2'><span className='pr-6'>2022-02-25</span>Barrowlands, Glasgow, UK</li>
                      <li className='pb-2'><span className='pr-6'>2022-02-25</span>Barrowlands, Glasgow, UK</li>
                      <li className='pb-2'><span className='pr-6'>2022-02-25</span>Barrowlands, Glasgow, UK</li>
                      <li className='pb-2'><span className='pr-6'>2022-02-25</span>Barrowlands, Glasgow, UK</li>
                  </ul>
              </div>
          </section>
          <section idName='more' className='lg:px-6'>
              <h1 className='font-bold'>hello</h1>
          </section>
      </main>

        <footer className='w-full flex justify-center text-zinc-400  font-bold text-l'>
        <a
            href="http://craigshewry.co.uk"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
            <span className='text-zinc-50 hover:text-zinc-600'>
              @craigmadethis
          </span>
        </a>
      </footer>
    </div>
  )
}
